// <auto-generated />
namespace YSVintageShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update18));
        
        string IMigrationMetadata.Id
        {
            get { return "201702081943261_Update18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
